import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import jwt_decode from "jwt-decode";

export const metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

interface IToken {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  role: string;
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const token = cookieStore.get("finance_token");

  if (!token) {
    return redirect("/login");
  } else {
    const user = jwt_decode(token.value) as IToken;

    return (
      <>
        <div>{user.name}</div>
        {children}
      </>
    );
  }
}
