import { BreadcrumbItemProps } from "@/components/Breadcrumbs/BreadcrumbItem";
import { Sidebar } from "@/components/sidebar";
import { FunctionComponentElement } from "react";

export const metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

interface IToken {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  role: string;
}

type MyType = {
  breadcrumbs: BreadcrumbItemProps[];
} & Record<string, any>;

export interface AuthLayoutProps {
  children: FunctionComponentElement<any>;
}

export default function AuthLayout(props: AuthLayoutProps) {
  return (
    <div className="flex">
      <Sidebar />
      {props.children}
    </div>
  );
}
