import { Sidebar } from "@/components/sidebar";
import { FunctionComponentElement } from "react";

export const metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

export interface AuthLayoutProps {
  children: FunctionComponentElement<any>;
}

export default function AuthLayout(props: AuthLayoutProps) {
  return (
    <div className="flex">
      <Sidebar />
      {props.children}
    </div>
  );
}
